[project]
name = "ggap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cartopy>=0.25.0",
    "earthengine-api>=1.6.13",
    "geemap>=0.36.5",
    "matplotlib>=3.10.6",
    "mpi4py>=4.1.1",
    "numpy>=2.3.3",
    "pip>=25.2",
    "rasterio>=1.4.3",
    "requests>=2.32.5",
    "scipy>=1.16.2",
    "shapely>=2.1.2",
]
